import {
  mdiVuejs,
  mdiLanguageGo,
  mdiLanguageTypescript,
  mdiGoogleCloud,
  mdiGoogleAnalytics,
  mdiFirebase,
  mdiLanguagePython,
  mdiAws,
  mdiKubernetes,
  mdiNodejs,
  mdiLanguageJava,
  mdiRabbit,
} from "@mdi/js";
import type { IProject } from "../types";

export const PROJECTS: IProject[] = [
  {
    title: "LG 익시 관리 도구",
    desc: "AI 모델 관리 및 서비스 제공 플랫폼",
    projType: "web",
    using: [mdiAws, mdiVuejs, mdiLanguageTypescript, mdiLanguageJava],
    to: "/project/list/ixi",
    titleImg: "/projects/ixi-admin/1.png",
    allImg: [
      "/projects/ixi-admin/1.png",
      "/projects/ixi-admin/2.png",
      "/projects/ixi-admin/3.png",
      "/projects/ixi-admin/4.png",
      "/projects/ixi-admin/5.png",
      "/projects/ixi-admin/6.png",
    ],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "SK 드론 관제 플랫폼",
    desc: "AI 모델 관리 및 서비스 제공 플랫폼",
    projType: "web",
    using: [mdiAws, mdiVuejs, mdiLanguageTypescript, mdiLanguageJava],
    to: "/project/list/ixi",
    titleImg: "/projects/ixi-admin/1.png",
    allImg: [
      "/projects/ixi-admin/1.png",
      "/projects/ixi-admin/2.png",
      "/projects/ixi-admin/3.png",
      "/projects/ixi-admin/4.png",
      "/projects/ixi-admin/5.png",
      "/projects/ixi-admin/6.png",
    ],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "LG 데이터 산업 플랫폼",
    desc: "AI 모델 관리 및 서비스 제공 플랫폼",
    projType: "web",
    using: [mdiAws, mdiVuejs, mdiLanguageTypescript, mdiLanguageJava],
    to: "/project/list/b2b-platform",
    allImg: [],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "Inout box",
    desc: "의류 소/도매 플랫폼",
    projType: "web",
    titleImg: "/projects/iobox/inout-login.png",
    using: [mdiVuejs, mdiLanguageGo, mdiLanguageTypescript, mdiGoogleCloud],
    usingDetail: [
      'api server: "Golang (Gin)"',
      'web server: "(Vue.js) firebase hosting"',
      'db: "firestore"',
    ],
    to: "/project/list/inout-box",
    allImg: [
      "/projects/iobox/inquiry.png",
      "/projects/iobox/shop-main.png",
      "/projects/iobox/uncle-main.png",
      "/projects/iobox/vendor-main.png",
    ],
    description: [
      "의류 산업(동대문 특화) 플랫폼 구축이 목적인 프로젝트.",
      "각 역할(소매/도매/사입)별 필요 기능들을 구축하여, 하나의 플랫폼에서 전자 상거래가 이루어 지는 것이 목표.",
      "소매의 경우 재고관리, 판매관리, 주문관리, 배송관리 등의 기능을 제공하며, 도매의 경우 상품등록, 주문관리, 배송관리, POS, 외상관리 등의 기능을 제공.",
      "사입의 경우, 도매와 계약된 사업자로 빠른 배송을 위한 기능을 제공(Mobile App).",
    ],
    myRole: "1인 개발",
    roleDetail: [
      "의류 종사자인 친구들의 기획과 요구사항을 바탕으로 혼자 개발.",
    ],
    earned: [
      `
      웹 서비스 도매 POS 기능으로부터 판매 정보에 대한 영수증 정보를 각 기기에서 출력 할 수 있어야 했습니다. 
      사업 성격상 영수증기기에서 바로 출력이 가능해야 했으나 브라우저의 프린트 서비스는 기기/브라우저별 해상도, 기타 미지원 기능, 스타일로 인해 깨지는 현상이 발생 하였습니다. 
      이에, 자주 사용되는 기기별 맞춤 dom 생성 및 css 적용을 통해 해결하였습니다.
      `,
      "App, Web(log, analytics), Server의 로그 중앙화(using GCP logging) 기능 구현 및 모니터링",
      "참여 동기였던 전체 서비스 A to Z 개발 경험을 통해, 개발자로서의 역량 향상.",
    ],
  },
  {
    title: "Inout uncle",
    desc: "의류 배송 플랫폼",
    projType: "app",
    titleImg: "/projects/iobox/app-store.jpeg",
    using: ["/icon/flutter-logo.svg", mdiGoogleCloud, mdiGoogleAnalytics],
    usingPubIdx: [0],
    to: "/project/list/inout-uncle",
    allImg: [
      "/projects/iobox/uncle-app-1.png",
      "/projects/iobox/uncle-app-2.png",
      "/projects/iobox/app-store.jpeg",
    ],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "Campi",
    desc: "캠핑 플랫폼",
    projType: "app",
    titleImg: "/projects/campi/my-page.jpg",
    using: ["/icon/flutter-logo.svg", mdiFirebase, mdiGoogleCloud],
    usingPubIdx: [0],
    whiteImg: true,
    to: "/project/list/campi",
    allImg: ["/projects/campi/feed.jpg", "/projects/campi/my-page.jpg"],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "Virtual try on backend",
    desc: "AI 부서로 부터 제작된 모델을 바탕으로, 웹 서비스 제작(국가 과제)",
    projType: "web",
    using: [mdiAws, mdiLanguagePython],
    titleImg: "/projects/try-on.png",
    allImg: ["/projects/try-on.png"],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "CJ 크롤러 제작",
    desc: "각종 쇼핑플랫폼에서 판매중인 CJ 제일제당 상품데이터 수집 및 ETL to cj",
    projType: "web",
    using: [mdiAws, mdiKubernetes, mdiLanguagePython],
    allImg: [],
    description: ["Argo Workflows를 사용하여 ETL 작업을 자동화"],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "쇼핑물 상품 추천 앱 제작",
    desc: "",
    projType: "app",
    using: [],
    usingDetail: [],
    allImg: [],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
  },
  {
    title: "사내 AI 모델 관리 시스템 개선 및 유지보수",
    desc: "",
    projType: "app",
    using: [
      mdiRabbit,
      mdiVuejs,
      mdiLanguageTypescript,
      mdiAws,
      mdiKubernetes,
      mdiLanguagePython,
    ],
    usingDetail: [
      'api server: "Python (Django)"',
      'web server: "(Vue.js) Jenkins, "',
    ],
    allImg: [],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
  },
  {
    title: "데이터 수집 및 NLP",
    desc: "Fashion Magazine 데이터 수집 및 키워드 추출 (TN-ITN 등)",
    projType: "web",
    using: [mdiLanguagePython],
    allImg: [],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "LOTTE 추천 어드민 페이지",
    desc: "롯데 홈쇼핑 추천서비스 어드민 페이지 제작",
    projType: "web",
    using: [mdiAws, mdiKubernetes, mdiVuejs, mdiLanguagePython],
    titleImg: "/projects/try-on.png",
    allImg: ["/projects/try-on.png"],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "회사 홈페이지 제작",
    desc: "PM & 개발 & 유지보수",
    projType: "web",
    titleImg: "/projects/intellisys.png",
    to: "http://intellisys.co.kr",
    using: [mdiNodejs, mdiVuejs],
    allImg: ["/projects/intellisys.png"],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
  {
    title: "개인 포트폴리오 사이트",
    desc: "블로그, 기술 연구, 프로젝트 기재",
    projType: "web",
    titleImg: "/projects/intellisys.png",
    to: "https://peachhub.love/home",
    using: [mdiNodejs, mdiVuejs],
    allImg: ["/projects/intellisys.png"],
    description: [],
    myRole: "",
    roleDetail: [],
    earned: [],
    usingDetail: [],
  },
];
const projectsHasImg = PROJECTS.filter((p) => p.allImg.length > 0);
export const getRandomProjectSingleImg = () => {
  const projIdx = Math.floor(Math.random() * projectsHasImg.length);
  const projectInfo = projectsHasImg[projIdx];
  const imgIdx = Math.floor(Math.random() * projectInfo.allImg.length);
  const imageSrc = projectInfo.allImg[imgIdx];
  return { projectInfo, imageSrc };
};

export default PROJECTS;
